In [1]:
import pandas as pd
import numpy as np

In [2]:
# lgb ver 64 
lgb = pd.read_csv("submission_lgb.csv")

# lgb ver 68 https://www.kaggle.com/taichin/riiid-lgbm-2nd?scriptVersionId=49887884
lgb_all = pd.read_csv("submission_lgb_all.csv")

# lgb ver 76
lgb_v76 = pd.read_csv("submission_lgb_v76.csv")

# lgb ver 77
lgb_v77 = pd.read_csv("submission_lgb_v77.csv")

# lgb ver 79
lgb_v79 = pd.read_csv("submission_lgb_v79.csv")

# my tabnet
tab = pd.read_csv("submission_tab.csv")

# https://www.kaggle.com/stevemju/riiid-simple-elo-rating
elo = pd.read_csv("submission_elo.csv")

# https://www.kaggle.com/leadbest/sakt-with-randomization-state-updates
sample_sakt = pd.read_csv("submission_sample_sakt.csv")

# https://www.kaggle.com/zephyrwang666/riiid-lgbm-bagging2
sample_lgb = pd.read_csv("submission_sample_lgb.csv")

#https://www.kaggle.com/gilfernandes/riiid-self-attention-transformer?select=submission.csv
transformer = pd.read_csv("submission_transformer.csv") 

In [15]:
np.corrcoef(lgb.answered_correctly.values, elo.answered_correctly.values)

array([[1.       , 0.9289907],
       [0.9289907, 1.       ]])

In [7]:
np.corrcoef(lgb.answered_correctly.values, sample_sakt.answered_correctly.values)

array([[1.        , 0.92191011],
       [0.92191011, 1.        ]])

In [18]:
np.corrcoef(lgb.answered_correctly.values, tab.answered_correctly.values)

array([[1.       , 0.9511597],
       [0.9511597, 1.       ]])

In [20]:
np.corrcoef(lgb_all.answered_correctly.values, elo.answered_correctly.values)

array([[1.        , 0.93672189],
       [0.93672189, 1.        ]])

In [9]:
np.corrcoef(lgb_all.answered_correctly.values, sample_sakt.answered_correctly.values)

array([[1.        , 0.92532806],
       [0.92532806, 1.        ]])

In [22]:
np.corrcoef(lgb_all.answered_correctly.values, tab.answered_correctly.values)

array([[1.        , 0.95274816],
       [0.95274816, 1.        ]])

In [3]:
np.corrcoef(sample_lgb.answered_correctly.values, sample_sakt.answered_correctly.values)

array([[1.        , 0.88676161],
       [0.88676161, 1.        ]])

In [10]:
np.corrcoef(lgb_all.answered_correctly.values, transformer.answered_correctly.values)

array([[1.        , 0.90589691],
       [0.90589691, 1.        ]])

In [11]:
np.corrcoef(lgb.answered_correctly.values, transformer.answered_correctly.values)

array([[1.      , 0.899097],
       [0.899097, 1.      ]])

In [3]:
np.corrcoef(lgb_v76.answered_correctly.values, transformer.answered_correctly.values)

array([[1.        , 0.90168353],
       [0.90168353, 1.        ]])

In [5]:
np.corrcoef(lgb_v77.answered_correctly.values, transformer.answered_correctly.values)
# transformerにはない、lecture関連の情報を入れたことで相関が低くなっている！

array([[1.        , 0.89425353],
       [0.89425353, 1.        ]])

In [3]:
np.corrcoef(lgb_v79.answered_correctly.values, transformer.answered_correctly.values)

array([[1.        , 0.89690442],
       [0.89690442, 1.        ]])

## 結論
transformerの方がsaktよりも相関が低く、PBも良いのでensembleとして良さそう。